### ISSUE TITLE
spring-react-angular-issue

### ISSUE THREAD

**Issue by BillySadge** [llupanar/pract#1]
https://github.com/llupanar/pract/blob/9519c581b1a502e788abc9485944d282fb20ee0a/backend-crudo/src/main/java/org/jpract/backendcrudo/controller/ClientController.java#L13-L16

Ну вместо того чтобы в каждом контроллере писать "/api/v1/"  можно прописать в `application.properties`
`server.servlet.context-path=/api/v1`
client тогда можно будет вынести в requestMapping
и тогда уже можно сделать чтобы выглядело вот так 
```
@RestController
@RequestMapping("/client")
public class ClientController {

    @GetMapping
    public List<Client> getClient(){
...
    }

    @GetMapping("/{passport_number}")
    public ResponseEntity<Client> getClientByPassNum (@PathVariable(value="passport_number")
...
    }
...
```

https://github.com/llupanar/pract/blob/9519c581b1a502e788abc9485944d282fb20ee0a/backend-crudo/src/main/java/org/jpract/backendcrudo/controller/ClientController.java#L21-L24
`@Autowired` излишен , когда только один конструктор

Ещё можно прожимать `Ctrl + Alt + L` (в идее) чтобы отформатировать файл.

https://github.com/llupanar/pract/blob/9519c581b1a502e788abc9485944d282fb20ee0a/frontend-react/src/App.js#L44-L45

`addJob` и `editJob Title ` Два компонента почти идентичные, может лучше тогда иметь один компонент который будет содержать  переменную которая будет передоваться в зависимости от `route`, и в зависимости от этой переменной уже определять что должен отображать компонент  
Например
```
export default function JobTitleForm({ isEditing = false }) {
...

<Route exact path="/add-job-title" element={<JobTitleForm isEditing={false} />} />
<Route exact path="/edit-job-title/:id" element={<JobTitleForm isEditing={true} />} />
```
ну и в самом компоненте:
```
useEffect(() => {
        if (isEditing) {
          ...
        }
    }, [isEditing, id]);

 const onSubmit = async (e) => {
        e.preventDefault();
        const url = isEditing ? http://localhost:8080/api/v1/job_title/${id} : "http://localhost:8080/api/v1/job_title";
        const method = isEditing ? "put" : "post";
        await axios[method](url, jobTitle);
        navigate(isEditing ? "/job-title" : "/");
    };

  <h2 className="text-center m-4">{isEditing ? "Edit" : "Register"} Job Title</h2>
```

**angular**
https://github.com/llupanar/pract/blob/9519c581b1a502e788abc9485944d282fb20ee0a/fronted-angular/src/app/services/client.service.ts#L9-L32
8 сервисов в которых просто crud методы, может стоит их вынести в какой-нибудь BaseService и наследоваться

```
... 
export class BaseService<T> {
 constructor(private http: HttpClient, private apiUrl: string) {}

 getAll(): Observable<T[]> {
    return this.http.get<T[]>(this.apiUrl);
 }

 getById(id: string): Observable<T> {
    return this.http.get<T>(`${this.apiUrl}/${id}`);
 }

 create(item: T): Observable<T> {
    return this.http.post<T>(this.apiUrl, item);
 }

 update(id: string, item: T): Observable<T> {
    return this.http.put<T>(`${this.apiUrl}/${id}`, item);
 }

 delete(id: string): Observable<void> {
    return this.http.delete<void>(`${this.apiUrl}/${id}`);
 }
}
```
и потом
```
export class ClientService extends BaseService<Client> {
 constructor(http: HttpClient) {
    super(http, .../client`);
 }
}
```
так же можно создать environment где где будет храниться базовый api url или другими способами (в реакте тоже можно сделать)

**Comment by llupanar** [comment]
Исправила
